#!/bin/sh

# Gradle startup script generated by Gradle.

set -e

APP_HOME="$(cd "${0%/*}" && pwd -P)"

if [ -n "$JAVA_HOME" ] ; then
    JAVA_BIN="$JAVA_HOME/bin/java"
else
    JAVA_BIN="java"
fi

exec "$JAVA_BIN" \
    -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
    org.gradle.wrapper.GradleWrapperMain "$@"
